# Generated by Django 5.2.9 on 2026-03-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nombre_uniforme", models.CharField(max_length=200)),
                (
                    "apellidos_uniforme",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("otras_formas_nombre", models.TextField(blank=True, default="")),
                (
                    "titulo_nobiliario",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("id_viaff", models.CharField(blank=True, max_length=100, null=True)),
                ("genero", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "fecha_nacimiento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "fecha_muerte",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("funcion", models.CharField(default="no músico", max_length=100)),
                (
                    "cargo_profesional",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "ordering": ["apellidos_uniforme", "nombre_uniforme"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("tipo_documento", models.CharField(max_length=200)),
                (
                    "fecha_documento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "lugar_documento",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "fecha_inicio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_fin", models.CharField(blank=True, max_length=50, null=True)),
                ("lugar", models.CharField(blank=True, max_length=500, null=True)),
                ("observaciones_lugar", models.TextField(blank=True, null=True)),
                ("texto", models.TextField(blank=True, null=True)),
                (
                    "seccion_administrativa_emision",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "seccion_administrativa_recepcion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("hora", models.CharField(blank=True, max_length=50, null=True)),
                ("luces", models.TextField(blank=True, null=True)),
                ("signatura", models.CharField(blank=True, max_length=200, null=True)),
                ("practica_musical", models.TextField(blank=True, null=True)),
                ("objeto_musical_desc", models.TextField(blank=True, null=True)),
                ("autor", models.CharField(blank=True, max_length=200, null=True)),
                ("mencion_musica", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("evento_descripcion", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "destinatario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_recibidos",
                        to="sonare_app.persona",
                    ),
                ),
                (
                    "emisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_emitidos",
                        to="sonare_app.persona",
                    ),
                ),
                (
                    "otras_personas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentos_citado",
                        to="sonare_app.persona",
                    ),
                ),
                (
                    "visto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_vistos",
                        to="sonare_app.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["fecha_documento"],
            },
        ),
    ]
