# Generated by Django 5.2.9 on 2026-03-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sonare_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=400)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hijos",
                        to="sonare_app.lugar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lugar",
                "verbose_name_plural": "Lugares",
                "ordering": ["padre__nombre", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="documento",
            name="lugar_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="sonare_app.lugar",
                verbose_name="Lugar (jerárquico)",
            ),
        ),
    ]
